<?php
/**
 * TL_ROOT/system/modules/literature/languages/ru/modules.php 
 * 
 * TYPOlight extension: literature 1.2.1 stable 
 * Russian translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Dmitry Kuznetsov (kuzmich), http://on.freedom-vrn.ru 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['literature']['0'] = "Список литературы";
$GLOBALS['TL_LANG']['MOD']['literature']['1'] = "Этот модуль позволяет создавать и управлять списком литературы.";
$GLOBALS['TL_LANG']['FMD']['literaturelist']['0'] = "Список литературы";
$GLOBALS['TL_LANG']['FMD']['literaturelist']['1'] = "Модуль показывает список литературы";
 
?>
