<?php
/**
 * TL_ROOT/system/modules/literature/languages/ru/tl_literature_category.php 
 * 
 * TYPOlight extension: literature 1.2.1 stable 
 * Russian translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Dmitry Kuznetsov (kuzmich), http://on.freedom-vrn.ru 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_literature_category']['title']['0'] = "Название";
$GLOBALS['TL_LANG']['tl_literature_category']['title']['1'] = "Пожалуйста, введите название категории.";
$GLOBALS['TL_LANG']['tl_literature_category']['description']['0'] = "Описание";
$GLOBALS['TL_LANG']['tl_literature_category']['description']['1'] = "Пожалуйста, введите описание категории.";
$GLOBALS['TL_LANG']['tl_literature_category']['tstamp']['0'] = "Последнее изменение";
$GLOBALS['TL_LANG']['tl_literature_category']['tstamp']['1'] = "Дата и время последнего изменения.";
$GLOBALS['TL_LANG']['tl_literature_category']['new']['0'] = "Добавить категорию";
$GLOBALS['TL_LANG']['tl_literature_category']['new']['1'] = "Добавить новую категорию";
$GLOBALS['TL_LANG']['tl_literature_category']['show']['0'] = "Детали";
$GLOBALS['TL_LANG']['tl_literature_category']['show']['1'] = "Показать детали категории ID %s";
$GLOBALS['TL_LANG']['tl_literature_category']['edit']['0'] = "Изменить категорию";
$GLOBALS['TL_LANG']['tl_literature_category']['edit']['1'] = "Изменить категорию ID %s";
$GLOBALS['TL_LANG']['tl_literature_category']['copy']['0'] = "Копировать категорию";
$GLOBALS['TL_LANG']['tl_literature_category']['copy']['1'] = "Копировать категорию ID %s";
$GLOBALS['TL_LANG']['tl_literature_category']['delete']['0'] = "Удалить категорию";
$GLOBALS['TL_LANG']['tl_literature_category']['delete']['1'] = "Удалить категорию ID %s";
 
?>
