<?php
/**
 * TL_ROOT/system/modules/literature/languages/ru/tl_literature.php 
 * 
 * TYPOlight extension: literature 1.2.1 stable 
 * Russian translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Dmitry Kuznetsov (kuzmich), http://on.freedom-vrn.ru 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_literature']['literature_type']['0'] = "Тип литературы";
$GLOBALS['TL_LANG']['tl_literature']['literature_type']['1'] = "Пожалуйста, выберите тип литературы.";
$GLOBALS['TL_LANG']['tl_literature']['literature_type']['periodic']['0'] = "Периодическая литература, журналы т.д.";
$GLOBALS['TL_LANG']['tl_literature']['literature_type']['periodic']['1'] = "Автор, A. A., Автор, B. B. & Автор, C. C. (1994). Название статьи. <u>Журнал, xx</u>, xxx-xxx.";
$GLOBALS['TL_LANG']['tl_literature']['literature_type']['nonperiodic']['0'] = "Не периодическая литература";
$GLOBALS['TL_LANG']['tl_literature']['literature_type']['nonperiodic']['1'] = "Автор, A. A. (1994). <u>Название литературы</u>. Место издания: Издатель.";
$GLOBALS['TL_LANG']['tl_literature']['literature_type']['nonperiodicpart']['0'] = "Части не периодической литературы (напр., главы книги)";
$GLOBALS['TL_LANG']['tl_literature']['literature_type']['nonperiodicpart']['1'] = "Автор, A. A. & Автор, B. B. (1994). Название главы. В редакции: A. Редактор, B. Редактор & C. Редактор (Редактор), <u>Название литературы</u> (p. xxx-xxx). Место издания: Издатель.";
$GLOBALS['TL_LANG']['tl_literature']['title']['0'] = "Название";
$GLOBALS['TL_LANG']['tl_literature']['title']['1'] = "Пожалуйста, введите название.";
$GLOBALS['TL_LANG']['tl_literature']['title_info']['0'] = "Дополнительная информация";
$GLOBALS['TL_LANG']['tl_literature']['title_info']['1'] = "Пожалуйста, введите дополнительную информацю (напр., издание)";
$GLOBALS['TL_LANG']['tl_literature']['title_source']['0'] = "Перевод / Медиа";
$GLOBALS['TL_LANG']['tl_literature']['title_source']['1'] = "Пожалуйста, введите перевод или медиа.";
$GLOBALS['TL_LANG']['tl_literature']['location']['0'] = "Место издания";
$GLOBALS['TL_LANG']['tl_literature']['location']['1'] = "Пожалуйста, введите место издания";
$GLOBALS['TL_LANG']['tl_literature']['publisher']['0'] = "Издатель";
$GLOBALS['TL_LANG']['tl_literature']['publisher']['1'] = "Пожалуйста, введите издателя";
$GLOBALS['TL_LANG']['tl_literature']['uri']['0'] = "Получено из";
$GLOBALS['TL_LANG']['tl_literature']['uri']['1'] = "Пожалуйста, введите адрес веб-страницы, гда литература имеется в наличии.";
$GLOBALS['TL_LANG']['tl_literature']['uri_date']['0'] = "Дата доступности";
$GLOBALS['TL_LANG']['tl_literature']['uri_date']['1'] = "Пожалуйста, введите дату доступности";
$GLOBALS['TL_LANG']['tl_literature']['released']['0'] = "Год издания";
$GLOBALS['TL_LANG']['tl_literature']['released']['1'] = "Пожалуйста, введите год издания.";
$GLOBALS['TL_LANG']['tl_literature']['title_act']['0'] = "Название литературы";
$GLOBALS['TL_LANG']['tl_literature']['title_act']['1'] = "Пожалуйста, введите название литературы.";
$GLOBALS['TL_LANG']['tl_literature']['title_act_info']['0'] = "Дополнительная информация";
$GLOBALS['TL_LANG']['tl_literature']['title_act_info']['1'] = "Пожалуйста, введите дополнительную информацию о литературе.";
$GLOBALS['TL_LANG']['tl_literature']['title_journal']['0'] = "Журнал";
$GLOBALS['TL_LANG']['tl_literature']['title_journal']['1'] = "Пожалуйста, введите название журнала.";
$GLOBALS['TL_LANG']['tl_literature']['volume']['0'] = "Номер (том)";
$GLOBALS['TL_LANG']['tl_literature']['volume']['1'] = "Пожалуйста, введите номер (том) журнала.";
$GLOBALS['TL_LANG']['tl_literature']['issue']['0'] = "Выпуск";
$GLOBALS['TL_LANG']['tl_literature']['issue']['1'] = "Пожалуйста, введите выпуск журнала.";
$GLOBALS['TL_LANG']['tl_literature']['pages']['0'] = "Страница ссылок";
$GLOBALS['TL_LANG']['tl_literature']['pages']['1'] = "Пожалуйста, введите страницу ссылок.";
$GLOBALS['TL_LANG']['tl_literature']['authors']['0'] = "Автор";
$GLOBALS['TL_LANG']['tl_literature']['authors']['1'] = "Пожалуйста, введите одного или несколько авторов.";
$GLOBALS['TL_LANG']['tl_literature']['editors']['0'] = "Редактор";
$GLOBALS['TL_LANG']['tl_literature']['editors']['1'] = "Пожалуйста, введите одного или несколько редакторов.";
$GLOBALS['TL_LANG']['tl_literature']['isbn']['0'] = "ISBN";
$GLOBALS['TL_LANG']['tl_literature']['isbn']['1'] = "Пожалуйста, введите ISBN номер.";
$GLOBALS['TL_LANG']['tl_literature']['tags']['0'] = "Теги";
$GLOBALS['TL_LANG']['tl_literature']['tags']['1'] = "Пожалуйста, введите один или несколько разделенных запятыми тегов, для классификации справочной литературы.";
$GLOBALS['TL_LANG']['tl_literature']['new']['0'] = "Добавить литературу";
$GLOBALS['TL_LANG']['tl_literature']['new']['1'] = "Добавить новую литературу";
$GLOBALS['TL_LANG']['tl_literature']['show']['0'] = "Детали";
$GLOBALS['TL_LANG']['tl_literature']['show']['1'] = "Показать детали литературы ID %s";
$GLOBALS['TL_LANG']['tl_literature']['edit']['0'] = "Изменить литературу";
$GLOBALS['TL_LANG']['tl_literature']['edit']['1'] = "Изменить литературу ID %s";
$GLOBALS['TL_LANG']['tl_literature']['editheader']['0'] = "Изменить категорию";
$GLOBALS['TL_LANG']['tl_literature']['editheader']['1'] = "Изменить родительскую категории";
$GLOBALS['TL_LANG']['tl_literature']['copy']['0'] = "Копировать литературу";
$GLOBALS['TL_LANG']['tl_literature']['copy']['1'] = "Копировать литературу ID %s";
$GLOBALS['TL_LANG']['tl_literature']['cut']['0'] = "Переместить литературу";
$GLOBALS['TL_LANG']['tl_literature']['cut']['1'] = "Переместить литературу ID %s";
$GLOBALS['TL_LANG']['tl_literature']['delete']['0'] = "Удалить литературу";
$GLOBALS['TL_LANG']['tl_literature']['delete']['1'] = "Удалить литературу ID %s";
$GLOBALS['TL_LANG']['tl_literature']['availableat'] = "Получено из";
$GLOBALS['TL_LANG']['tl_literature']['in'] = "В";
$GLOBALS['TL_LANG']['tl_literature']['pageshort'] = "стр.";
$GLOBALS['TL_LANG']['tl_literature']['firstname'] = "Имя";
$GLOBALS['TL_LANG']['tl_literature']['lastname'] = "Фамилия";
$GLOBALS['TL_LANG']['tl_literature']['editorShort'] = "Ред.";
$GLOBALS['TL_LANG']['tl_literature']['editorsShort'] = "Под ред.";
$GLOBALS['TL_LANG']['tl_literature']['addSelection'] = "Добавить выбранное";
$GLOBALS['TL_LANG']['tl_literature']['cancel'] = "Отмена";
$GLOBALS['TL_LANG']['tl_literature']['newList'] = "Добавить список";
$GLOBALS['TL_LANG']['tl_literature']['add'] = "Добавить";
$GLOBALS['TL_LANG']['tl_literature']['addLiterature'] = "Добавить литературу";
$GLOBALS['TL_LANG']['tl_literature']['removeList'] = "Удалить список";
$GLOBALS['TL_LANG']['tl_literature']['confirmRemoveList'] = "Вы действительно хотите удалить список?";
$GLOBALS['TL_LANG']['tl_literature']['removeSelected'] = "Перенести выбранное";
$GLOBALS['TL_LANG']['tl_literature']['errNoISBN'] = "Поле %s, следует указать ISBN номер (ISBN-10 или ISBN-13)";
$GLOBALS['TL_LANG']['tl_literature']['errWrongISBN10'] = "Ошибка контрольной суммы! Поле %s, следует исправить ISBN-10 номер";
$GLOBALS['TL_LANG']['tl_literature']['errWrongISBN13'] = "Ошибка контрольной суммы! Поле %s, следует исправить ISBN-13 номер";
$GLOBALS['TL_LANG']['tl_literature']['type_legend'] = "Тип литературы";
$GLOBALS['TL_LANG']['tl_literature']['authors_legend'] = "Авторы";
$GLOBALS['TL_LANG']['tl_literature']['editors_legend'] = "Редакторы";
$GLOBALS['TL_LANG']['tl_literature']['book_legend'] = "Описание и издатель";
$GLOBALS['TL_LANG']['tl_literature']['nonperiodic_legend'] = "Дата выпуска, литературные данные и издатель";
$GLOBALS['TL_LANG']['tl_literature']['periodic_legend'] = "Дата выпуска, журнальные данные и издатель";
$GLOBALS['TL_LANG']['tl_literature']['nonperiodicpart_legend'] = "Дата выпуска и литературные данные";
$GLOBALS['TL_LANG']['tl_literature']['tags_legend'] = "Метки";
$GLOBALS['TL_LANG']['tl_literature']['isbn_legend'] = "ISBN Number";
$GLOBALS['TL_LANG']['tl_literature']['uri_legend'] = "Справочная информация в сети";
 
?>
