<?php
/**
 * TL_ROOT/system/modules/literature/languages/ru/tl_module.php 
 * 
 * TYPOlight extension: literature 1.2.1 stable 
 * Russian translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Dmitry Kuznetsov (kuzmich), http://on.freedom-vrn.ru 
 * 
 * This file was created automatically be the TYPOlight extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_module']['lit_template']['0'] = "Стиль ссылки";
$GLOBALS['TL_LANG']['tl_module']['lit_template']['1'] = "Пожалуйста, выберите схему вывода литературы. Вы можете добавить выборочную схему <em>litref_</em> в папку <em>templates</em>.";
$GLOBALS['TL_LANG']['tl_module']['lit_categories']['0'] = "Категории";
$GLOBALS['TL_LANG']['tl_module']['lit_categories']['1'] = "Пожалуйста, выберите одну или несколько категорий для создания списка литературы.";
$GLOBALS['TL_LANG']['tl_module']['lit_listtitle']['0'] = "Название списка";
$GLOBALS['TL_LANG']['tl_module']['lit_listtitle']['1'] = "Пожалуйста, введите название списка литературы.";
$GLOBALS['TL_LANG']['tl_module']['lit_showsort']['0'] = "Сортировка";
$GLOBALS['TL_LANG']['tl_module']['lit_showsort']['1'] = "Выберите опцию, для сортировки списка литературы.";
$GLOBALS['TL_LANG']['tl_module']['lit_sort']['0'] = "Сортировать";
$GLOBALS['TL_LANG']['tl_module']['lit_sort']['1'] = "Пожалуйста, выберите вариант сортировки списка литературы.";
$GLOBALS['TL_LANG']['tl_module']['lit_sort']['title']['0'] = "По названию";
$GLOBALS['TL_LANG']['tl_module']['lit_sort']['title']['1'] = "Выберите эту опцию, чтобы отсортировать список литературы по названию.";
$GLOBALS['TL_LANG']['tl_module']['lit_sort']['released']['0'] = "По дате";
$GLOBALS['TL_LANG']['tl_module']['lit_sort']['released']['1'] = "Выберите эту опцию, чтобы отсортировать список литературы по дате выпуска.";
$GLOBALS['TL_LANG']['tl_module']['lit_sortorder']['0'] = "Упорядочить";
$GLOBALS['TL_LANG']['tl_module']['lit_sortorder']['1'] = "Пожалуйста, выберите порядок сортировки списка литературы.";
$GLOBALS['TL_LANG']['tl_module']['lit_sortorder']['asc']['0'] = "По возрастанию";
$GLOBALS['TL_LANG']['tl_module']['lit_sortorder']['asc']['1'] = "Выберите опцию, чтобы использовать сортировку по возрастанию.";
$GLOBALS['TL_LANG']['tl_module']['lit_sortorder']['desc']['0'] = "По убыванию";
$GLOBALS['TL_LANG']['tl_module']['lit_sortorder']['desc']['1'] = "Выберите опцию, чтобы использовать сортировку по убыванию.";
$GLOBALS['TL_LANG']['tl_module']['lit_tags']['0'] = "Теги";
$GLOBALS['TL_LANG']['tl_module']['lit_tags']['1'] = "Пожалуйста, введите один или несколько разделенных запятыми тегов, для классификации справочной литературы.";
$GLOBALS['TL_LANG']['tl_module']['pagetype']['literature'] = "Список литературы";
 
?>
