services:
    contao_literature.listener.insert_tags:
        class: Hschottm\LiteratureBundle\EventListener\InsertTagsListener
        arguments:
            - "@contao.framework"
        public: true