<?php
/**
 * TL_ROOT/system/modules/literature/languages/de/modules.php 
 * 
 * Contao extension: literature 1.4.0 beta1 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['MOD']['literature']['0'] = "Literaturverwaltung";
$GLOBALS['TL_LANG']['MOD']['literature']['1'] = "Mit diesem Modul können Sie Literaturverweise anlegen und verwalten.";
$GLOBALS['TL_LANG']['FMD']['literaturelist']['0'] = "Literaturliste";
$GLOBALS['TL_LANG']['FMD']['literaturelist']['1'] = "Dieses Modul zeigt eine Literaturliste an.";
$GLOBALS['TL_LANG']['FMD']['literaturesearch']    = array('Literatursuche', 'Mit diesem Modul können Sie Ihre Literaturdatenbank durchsuchen.');

?>
