<?php
/**
 * TL_ROOT/system/modules/literature/languages/de/tl_literature.php 
 * 
 * Contao extension: literature 1.4.0 beta1 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_literature']['literature_type']['0'] = "Literaturtyp";
$GLOBALS['TL_LANG']['tl_literature']['literature_type']['1'] = "Bitte wählen Sie den Literaturtyp aus.";
$GLOBALS['TL_LANG']['tl_literature']['literature_type']['periodic']['0'] = "Periodisch erscheinende Zeitschriften etc.";
$GLOBALS['TL_LANG']['tl_literature']['literature_type']['periodic']['1'] = "Autor, A. A., Autor, B. B. & Autor, C. C. (1994). Titel des Artikels. <u>Titel der Zeitschrift, xx</u>, xxx-xxx.";
$GLOBALS['TL_LANG']['tl_literature']['literature_type']['nonperiodic']['0'] = "Nicht-periodisch erscheinende Werke";
$GLOBALS['TL_LANG']['tl_literature']['literature_type']['nonperiodic']['1'] = "Autor, A. A. (1994). <u>Titel der Arbeit</u>. Ort: Verlag.";
$GLOBALS['TL_LANG']['tl_literature']['literature_type']['nonperiodicpart']['0'] = "Teile eines nicht-periodisch erscheinenden Werkes (z.B. Buchkapitel)";
$GLOBALS['TL_LANG']['tl_literature']['literature_type']['nonperiodicpart']['1'] = "Autor, A. A. & Autor, B. B. (1994). Titel des Kapitels. In: A. Herausgeber, B. Herausgeber & C. Herausgeber (Hrsg.), <u>Titel des Buches</u> (S. xxx-xxx). Ort: Verlag.";
$GLOBALS['TL_LANG']['tl_literature']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_literature']['title']['1'] = "Bitte geben Sie den Titel des Literaturverweises ein.";
$GLOBALS['TL_LANG']['tl_literature']['title_info']['0'] = "Zusatzinformationen";
$GLOBALS['TL_LANG']['tl_literature']['title_info']['1'] = "Bitte geben Sie Zusatzinformationen (z.B. die Auflage) ein.";
$GLOBALS['TL_LANG']['tl_literature']['title_source']['0'] = "Übers./Medien";
$GLOBALS['TL_LANG']['tl_literature']['title_source']['1'] = "Bitte geben Sie Übersetzungen oder Medien ein.";
$GLOBALS['TL_LANG']['tl_literature']['location']['0'] = "Ort";
$GLOBALS['TL_LANG']['tl_literature']['location']['1'] = "Bitte geben Sie den Ort ein.";
$GLOBALS['TL_LANG']['tl_literature']['publisher']['0'] = "Verlag";
$GLOBALS['TL_LANG']['tl_literature']['publisher']['1'] = "Bitte geben Sie den Verlag ein.";
$GLOBALS['TL_LANG']['tl_literature']['uri']['0'] = "Verfügbar unter";
$GLOBALS['TL_LANG']['tl_literature']['uri']['1'] = "Bitte geben Sie eine URL ein, unter der der Literaturverweis verfügbar ist.";
$GLOBALS['TL_LANG']['tl_literature']['uri_date']['0'] = "Datum des Zugriffs";
$GLOBALS['TL_LANG']['tl_literature']['uri_date']['1'] = "Bitte geben Sie das Datum des letzten Zugriffs auf die URL an.";
$GLOBALS['TL_LANG']['tl_literature']['released']['0'] = "Erscheinungsdatum";
$GLOBALS['TL_LANG']['tl_literature']['released']['1'] = "Bitte geben Sie das Erscheinungsdatum bzw. das Erscheinungsjahr ein.";
$GLOBALS['TL_LANG']['tl_literature']['title_act']['0'] = "Titel des Werkes";
$GLOBALS['TL_LANG']['tl_literature']['title_act']['1'] = "Bitte geben Sie den Titel des Werkes ein.";
$GLOBALS['TL_LANG']['tl_literature']['title_act_info']['0'] = "Zusatzinformationen";
$GLOBALS['TL_LANG']['tl_literature']['title_act_info']['1'] = "Bitte geben Zusatzinformationen zum Werk ein.";
$GLOBALS['TL_LANG']['tl_literature']['title_journal']['0'] = "Titel der Zeitschrift";
$GLOBALS['TL_LANG']['tl_literature']['title_journal']['1'] = "Bitte geben Sie den Titel der Zeitschrift ein.";
$GLOBALS['TL_LANG']['tl_literature']['volume']['0'] = "Band";
$GLOBALS['TL_LANG']['tl_literature']['volume']['1'] = "Bitte geben Sie den Band der Zeitschrift ein.";
$GLOBALS['TL_LANG']['tl_literature']['issue']['0'] = "Heftnummer";
$GLOBALS['TL_LANG']['tl_literature']['issue']['1'] = "Bitte geben Sie die Heftnummer der Zeitschrift ein.";
$GLOBALS['TL_LANG']['tl_literature']['pages']['0'] = "Seitenangabe";
$GLOBALS['TL_LANG']['tl_literature']['pages']['1'] = "Bitte geben Sie eine Seitenangabe ein.";
$GLOBALS['TL_LANG']['tl_literature']['authors']['0'] = "Autoren";
$GLOBALS['TL_LANG']['tl_literature']['authors']['1'] = "Bitte geben Sie einen oder mehrere Autoren ein.";
$GLOBALS['TL_LANG']['tl_literature']['editors']['0'] = "Herausgeber";
$GLOBALS['TL_LANG']['tl_literature']['editors']['1'] = "Bitte geben Sie einen oder mehrere Herausgeber ein.";
$GLOBALS['TL_LANG']['tl_literature']['isbn']['0'] = "ISBN";
$GLOBALS['TL_LANG']['tl_literature']['isbn']['1'] = "Bitte geben Sie die ISBN-Nummer ein.";
$GLOBALS['TL_LANG']['tl_literature']['issn']['0'] = "ISSN";
$GLOBALS['TL_LANG']['tl_literature']['issn']['1'] = "Bitte geben Sie die ISSN-Nummer ein.";
$GLOBALS['TL_LANG']['tl_literature']['tags']['0'] = "Auszeichnungen";
$GLOBALS['TL_LANG']['tl_literature']['tags']['1'] = "Bitte geben Sie eine oder mehrere Auszeichnungen durch Komma getrennt an, um den Literaturverweis zu kategorisieren.";
$GLOBALS['TL_LANG']['tl_literature']['abstract']['0'] = "Inhaltsangabe";
$GLOBALS['TL_LANG']['tl_literature']['abstract']['1'] = "Bitte geben Sie eine Inhaltsangabe für die Publikation an.";
$GLOBALS['TL_LANG']['tl_literature']['new']['0'] = "Neuer Literaturverweis";
$GLOBALS['TL_LANG']['tl_literature']['new']['1'] = "Einen neuen Literaturverweis anlegen";
$GLOBALS['TL_LANG']['tl_literature']['show']['0'] = "Details";
$GLOBALS['TL_LANG']['tl_literature']['show']['1'] = "Details des Literaturverweises ID %s anzeigen";
$GLOBALS['TL_LANG']['tl_literature']['edit']['0'] = "Literaturverweis bearbeiten";
$GLOBALS['TL_LANG']['tl_literature']['edit']['1'] = "Literaturverweis ID %s bearbeiten";
$GLOBALS['TL_LANG']['tl_literature']['editheader']['0'] = "Kategorie bearbeiten";
$GLOBALS['TL_LANG']['tl_literature']['editheader']['1'] = "Die übergeordnete Kategorie bearbeiten";
$GLOBALS['TL_LANG']['tl_literature']['copy']['0'] = "Literaturverweis duplizieren";
$GLOBALS['TL_LANG']['tl_literature']['copy']['1'] = "Literaturverweis ID %s duplizieren";
$GLOBALS['TL_LANG']['tl_literature']['cut']['0'] = "Literaturverweis verschieben";
$GLOBALS['TL_LANG']['tl_literature']['cut']['1'] = "Literaturverweis ID %s verschieben";
$GLOBALS['TL_LANG']['tl_literature']['delete']['0'] = "Literaturverweis löschen";
$GLOBALS['TL_LANG']['tl_literature']['delete']['1'] = "Literaturverweis ID %s löschen";
$GLOBALS['TL_LANG']['tl_literature']['availableat'] = "Verfügbar unter";
$GLOBALS['TL_LANG']['tl_literature']['in'] = "In";
$GLOBALS['TL_LANG']['tl_literature']['pageshort'] = "S.";
$GLOBALS['TL_LANG']['tl_literature']['firstname'] = "Vorname";
$GLOBALS['TL_LANG']['tl_literature']['lastname'] = "Nachname";
$GLOBALS['TL_LANG']['tl_literature']['editorShort'] = "Hrsg.";
$GLOBALS['TL_LANG']['tl_literature']['editorsShort'] = "Hrsg.";
$GLOBALS['TL_LANG']['tl_literature']['addSelection'] = "Auswahl hinzufügen";
$GLOBALS['TL_LANG']['tl_literature']['cancel'] = "Abbrechen";
$GLOBALS['TL_LANG']['tl_literature']['newList'] = "Neue Liste";
$GLOBALS['TL_LANG']['tl_literature']['add'] = "Hinzufügen";
$GLOBALS['TL_LANG']['tl_literature']['addLiterature'] = "Literatur hinzufügen";
$GLOBALS['TL_LANG']['tl_literature']['removeList'] = "Liste entfernen";
$GLOBALS['TL_LANG']['tl_literature']['confirmRemoveList'] = "Wollen Sie die Liste wirklich entfernen?";
$GLOBALS['TL_LANG']['tl_literature']['removeSelected'] = "Auswahl entfernen";
$GLOBALS['TL_LANG']['tl_literature']['errNoISBN'] = "Das Feld %s muss eine ISBN-Nummer beinhalten (entweder ISBN-10 oder ISBN-13)";
$GLOBALS['TL_LANG']['tl_literature']['errWrongISSN'] = "Das Feld %s muss eine korrekte ISSN-Nummer beinhalten. Leider stimmt die Prüfsumme nicht";
$GLOBALS['TL_LANG']['tl_literature']['errWrongISSNFormat'] = "Das Feld %s muss eine gültige ISSN-Nummer im Format xxxx-xxxx beinhalten (x = Zahl zwischen 0 und 9)";
$GLOBALS['TL_LANG']['tl_literature']['errWrongISBN10'] = "Das Feld %s muss eine korrekte ISBN10-Nummer beinhalten. Leider stimmt die Prüfsumme nicht";
$GLOBALS['TL_LANG']['tl_literature']['errWrongISBN13'] = "Das Feld %s muss eine korrekte ISBN10-Nummer beinhalten. Leider stimmt die Prüfsumme nicht";
$GLOBALS['TL_LANG']['tl_literature']['addImage']['0'] = "Ein Bild hinzufügen";
$GLOBALS['TL_LANG']['tl_literature']['addImage']['1'] = "Dem Verweis ein Bild hinzufügen.";
$GLOBALS['TL_LANG']['tl_literature']['addDownloads']['0'] = "Downloads hinzufügen";
$GLOBALS['TL_LANG']['tl_literature']['addDownloads']['1'] = "Dem Verweis Downloads hinzufügen.";
$GLOBALS['TL_LANG']['tl_literature']['downtitle']['0'] = "Überschrift";
$GLOBALS['TL_LANG']['tl_literature']['downtitle']['1'] = "Geben Sie eine Überschrift für die Downloads an.";
$GLOBALS['TL_LANG']['tl_literature']['literaturefile']['0'] = "Quelldatei";
$GLOBALS['TL_LANG']['tl_literature']['literaturefile']['1'] = "Bitte wählen Sie eine oder mehrere BibTeX-Dateien im .bib Format von Ihrem Gerät aus.";
$GLOBALS['TL_LANG']['tl_literature']['import']['0'] = "Importieren";
$GLOBALS['TL_LANG']['tl_literature']['import']['1'] = "Literaturverweise importieren";
$GLOBALS['TL_LANG']['tl_literature']['type_legend'] = "Literaturtyp";
$GLOBALS['TL_LANG']['tl_literature']['authors_legend'] = "Autoren";
$GLOBALS['TL_LANG']['tl_literature']['editors_legend'] = "Herausgeber";
$GLOBALS['TL_LANG']['tl_literature']['book_legend'] = "Buchdaten und Verlag";
$GLOBALS['TL_LANG']['tl_literature']['nonperiodic_legend'] = "Erscheinungsdatum, Literaturdaten und Verlag";
$GLOBALS['TL_LANG']['tl_literature']['periodic_legend'] = "Erscheinungsdatum, Zeitschriftendaten und Verlag";
$GLOBALS['TL_LANG']['tl_literature']['nonperiodicpart_legend'] = "Erscheinungsdatum und Literaturdaten";
$GLOBALS['TL_LANG']['tl_literature']['tags_legend'] = "Auszeichnungen";
$GLOBALS['TL_LANG']['tl_literature']['isbn_legend'] = "Identifikation";
$GLOBALS['TL_LANG']['tl_literature']['uri_legend'] = "Internet-Verweise";
$GLOBALS['TL_LANG']['tl_literature']['image_legend'] = "Bild-Einstellungen";
$GLOBALS['TL_LANG']['tl_literature']['downloads_legend'] = "Download-Einstellungen";
$GLOBALS['TL_LANG']['tl_literature']['abstract_legend'] = "Inhaltsangabe";
 
?>
