<?php
/**
 * TL_ROOT/system/modules/literature/languages/de/tl_literature_category.php 
 * 
 * Contao extension: literature 1.4.0 beta1 
 * Deutsch translation file 
 * 
 * Copyright : &copy; Helmut Schottmüller 
 * License   : GNU Lesser Public License (LGPL) 
 * Author    : Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * Translator: Helmut Schottmüller (hschottm), http://www.aurealis.de 
 * 
 * This file was created automatically be the Contao extension repository translation module.
 * Do not edit this file manually. Contact the author or translator for this module to establish 
 * permanent text corrections which are update-safe. 
 */
 
$GLOBALS['TL_LANG']['tl_literature_category']['title']['0'] = "Titel";
$GLOBALS['TL_LANG']['tl_literature_category']['title']['1'] = "Bitte geben Sie den Titel der Kategorie ein.";
$GLOBALS['TL_LANG']['tl_literature_category']['description']['0'] = "Beschreibung";
$GLOBALS['TL_LANG']['tl_literature_category']['description']['1'] = "Bitte geben Sie eine Beschreibung für die Kategorie ein.";
$GLOBALS['TL_LANG']['tl_literature_category']['tstamp']['0'] = "Zuletzt geändert";
$GLOBALS['TL_LANG']['tl_literature_category']['tstamp']['1'] = "Datum und Uhrzeit der letzten Änderung der Kategorie.";
$GLOBALS['TL_LANG']['tl_literature_category']['new']['0'] = "Neue Kategorie";
$GLOBALS['TL_LANG']['tl_literature_category']['new']['1'] = "Eine neue Kategorie anlegen";
$GLOBALS['TL_LANG']['tl_literature_category']['show']['0'] = "Kategoriedetails";
$GLOBALS['TL_LANG']['tl_literature_category']['show']['1'] = "Details der Kategorie ID %s anzeigen";
$GLOBALS['TL_LANG']['tl_literature_category']['edit']['0'] = "Kategorie bearbeiten";
$GLOBALS['TL_LANG']['tl_literature_category']['edit']['1'] = "Kategorie ID %s bearbeiten";
$GLOBALS['TL_LANG']['tl_literature_category']['copy']['0'] = "Kategorie duplizieren";
$GLOBALS['TL_LANG']['tl_literature_category']['copy']['1'] = "Kategorie ID %s duplizieren";
$GLOBALS['TL_LANG']['tl_literature_category']['delete']['0'] = "Kategorie löschen";
$GLOBALS['TL_LANG']['tl_literature_category']['delete']['1'] = "Kategorie ID %s löschen";
 
?>
